project:
  type: website
  output-dir: _site

website:
  title: "Terlipressin HARMONY Registry"
  navbar:
    background: "#2c8dbb"
    foreground: white
    left:
      - href: index.qmd
        text: Summary
      - href: redcap_variables.qmd
        text: REDCap Variables
      - href: derived_variables.qmd
        text: Derived Variables
      - href: data_summary.qmd
        text: Data Summary
      - href: bug_audit.qmd
        text: Code Check

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: right
    code-fold: true
    self-contained: false
